//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushuRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public int Id { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public string Link { get; set; }
    }
}
