//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushuRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogTablesView
    {
        public int Id { get; set; }
        public Nullable<int> HallId { get; set; }
        public string HallName { get; set; }
        public int Number { get; set; }
        public Nullable<bool> VIP { get; set; }
    }
}
