//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushuRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCall
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public string СlientName { get; set; }
        public string ClientPhone { get; set; }
        public Nullable<System.DateTime> FromTimeCall { get; set; }
        public Nullable<System.DateTime> ToTimeCall { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    }
}
